server {
    listen 80;
    server_name videosplice.weiwei.website;

    root /var/www/videosplice.weiwei.website;
    index index.html;

    location / {
        add_header Cross-Origin-Opener-Policy "same-origin" always;
        add_header Cross-Origin-Embedder-Policy "require-corp" always;
        try_files $uri $uri/ /index.html;
    }
}